
POST http://localhost:3000/events
Content-Type: application/json

{
  "title": "my event",
  "details": "some datails",
  "maximumAttendees": 10
}

###
POST http://localhost:3000/events/04315cd2-c080-41db-bf65-9f37de21de64/attendees
Content-Type: application/json

{
  "name": "john doe",
  "email": "johndoe@example.com"
}


###
GET http://localhost:3000/events/04315cd2-c080-41db-bf65-9f37de21de64

###
GET http://localhost:3000/attendees/59c47b9c-3859-4d36-ba7a-6bee3be43aec/badge

###
GET http://localhost:3000/attendees/59c47b9c-3859-4d36-ba7a-6bee3be43aec/checkIn

###
GET http://localhost:3000/events/04315cd2-c080-41db-bf65-9f37de21de64/attendees



