
POST http://localhost:3000/events
Content-Type: application/json

{
  "title": "my event",
  "details": "some datails",
  "maximumAttendees": 10
}

###
POST http://localhost:3000/events/ec71f4c6-b696-4e4f-a467-81663a7ab893/attendees
Content-Type: application/json

{
  "name": "john doe",
  "email": "johndoe@example.com"
}


###
GET http://localhost:3000/events/ec71f4c6-b696-4e4f-a467-81663a7ab893

###
GET http://localhost:3000/attendees/2/badge

###
GET http://localhost:3000/attendees/4/checkIn

###
GET http://localhost:3000/events/ec71f4c6-b696-4e4f-a467-81663a7ab893/attendees



