
POST http://localhost:3000/events
Content-Type: application/json

{
  "title": "my event",
  "details": "some datails",
  "maximumAttendees": 10
}

###
POST http://localhost:3000/events/c8f7858a-6d38-443b-b3d6-ae499d6e59cc/attendees
Content-Type: application/json

{
  "name": "john doe",
  "email": "johndoe@example.com"
}


###
GET http://localhost:3000/events/c8f7858a-6d38-443b-b3d6-ae499d6e59cc

###
GET http://localhost:3000/attendees/2/badge

###
GET http://localhost:3000/attendees/2/checkIn

###
GET http://localhost:3000/events/ec71f4c6-b696-4e4f-a467-81663a7ab893/attendees



