version: "3.7"

services:
  nlw-db:
    image: postgres
    container_name: nlw-15-node
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=mydb
    ports:
      - 5432:5432
